### ISSUE TITLE
GDPR compliance is missing

### ISSUE THREAD

**Issue by dvdcastro** [intelliboard/intelliboard#12]
Hello,

We've found that GDPR compliance is missing on your plugin.

These tables hold user data:
`local_intelliboard_tracking`
`local_intelliboard_assign`

See:
https://docs.moodle.org/dev/Privacy_API#Describing_data_stored_in_database_tables
https://docs.moodle.org/dev/Privacy_API#Providing_a_way_to_export_user_data

And your plugin is also not reporting that it shares data with an external location.
See:
https://docs.moodle.org/dev/Privacy_API#Indicating_that_you_export_data_to_an_external_location

You can use these utility scripts to verify if your plugin is correctly complying with GDPR:
https://docs.moodle.org/dev/Privacy_API/Utilities

**Comment by intelliboard** [comment]
Logs:

== local_intelliboard (local_intelliboard\privacy\provider) ==
Processing local_intelliboard (395/462) (Friday, 25 May 2018, 10:25 am)
