### ISSUE TITLE
PHP 7 privacy provider included.

### ISSUE THREAD

**Issue by danmarsden** [intelliboard/intelliboard#16]
You have added a privacy provider class that requires php 7 and will cause a fatal error in Moodle 3.3 and in Moodle 3.1/3.2 the class probably shouldn't even be there.

If you want to use the PHP 7 stuff you must branch your code and provide a different version for Moodle 3.3.

If you want to maintain the same privacy class for Moodle 3.3 and your master branch you must use the polyfill:
https://docs.moodle.org/dev/Privacy_API#What_to_do_if_you_have_one_plugin_that_supports_multiple_branches

**Comment by intelliboard** [comment]
Hi, I am not sure I understand your question correctly, the Privacy API is available in Moodle 3.5 and up. We tested the plugin on Moodle 3.0 and up with php 5.6/7.  So the code with "privacy provider class" on Moodle 3.3 won't use at all, please correct me if I missed something.

**Comment by danmarsden** [comment]
you have one git branch for all moodle versions and you have released this code in the plugins db for all moodle versions.
https://moodle.org/plugins/local_intelliboard
2.8, 2.9, 3.0, 3.1, 3.2, 3.3, 3.4, 3.5

The core privacy API is in Moodle 3.3 and higher(not just in Moodle 3.5). Moodle 3.3 does not require PHP 7 so you must use a slightly different format for the privacy provider class for Moodle 3.3 or if you want to use a shared codebase for Moodle 3.3 and higher you must use the polyfill as described in the link I gave above.

The privacy provider class you have included in your code requires PHP 7 and will not work in Moodle 3.3 (and should not be there at all for Moodle 3.2 and lower versions) - We run a php lint check prior to deployment on a site and the lint check fails because you have used the PHP 7 version of the privacy class which should only be used in Moodle 3.4 and higher.

If you want to use the same code-base with a single branch to support the privacy class for Moodle 3.3 you must use the polyfill as mentioned in the moodledocs link I gave above. 

I would also suggest you stop trying to support all Moodle versions on a single "master" branch - the privacy provider class should not be in your codebase for Moodle 3.2 and lower versions.

does that help?

**Comment by intelliboard** [comment]
Yes thanks, we'll make the necessary changes soon.

**Comment by intelliboard** [comment]
We created a new branch for Moodle 3.3 https://github.com/intelliboard/intelliboard/tree/MOODLE_33_STABLE_PHP5

**Comment by danmarsden** [comment]
will you also be created a branch for 3.2 and lower that excludes the privacy class? - Moodle 3.1 is still supported for another 11 Months and the privacy provider class shouldn't be in the plugin for Moodle 3.1 (or 3.2)

**Comment by intelliboard** [comment]
Yes, this is a link https://github.com/intelliboard/intelliboard/tree/MOODLE_31_STABLE_PHP5
