### ISSUE TITLE
Official API documentation?

### ISSUE THREAD

**Issue by ywarnier** [intelliboard/intelliboard#18]
Hi,

This looks like a copy/hack of the BBB plugin, still maintaining *a lot* of variables and database parameters names from the BigBlueButton plugin.

If I want to integrate Intelliboard into another LMS, is there an official API documentation page somewhere that I can use rather to try and debunk what is needed and what is not in this plugin in order to avoid carrying all that BBB stuff with me?

**Comment by intelliboard** [comment]
Hello,
Thank you for your question.

IntelliBoard does not provide open API to connect LMSs. We current support Moodle LMS and support for BigBlueButton within Moodle is based on activity level reporting. BigBlueButton reports are supported through native BBB events which we use to build reports on.

If you are interested in connecting your LMS to IntelliBoard, please contact us at support@intelliboard.net. Our representative will get in touch with you to discuss this opportunity.

Thank you,
IntelliBoard, Inc
