### ISSUE TITLE
MySQL specific functions used in almost all queries

### ISSUE THREAD

**Issue by crmpicco** [intelliboard/intelliboard#19]
Hi, I'm from the MoodleCloud team. We've been told that the intelliboard plugin is now compatible with Postgres, however, looking at the file: `externallib.php` there are over 100 uses of the function `FROM_UNIXTIME` - which is a MySQL specific function. We also spotted `PERIOD_DIFF` and `DATE_FORMAT` - both of which are not available in Postgres.

It looks to us as though this plugin will not work on a Postgres Moodle site. Can you confirm whether or not Postgres is supported?

Cheers,
Cameron Ball
cameron@moodle.com
Analyst Developer, Moodle HQ

_Note: I am submitting this on behalf of Cameron_

**Comment by cameorn1730** [comment]
Closing this as I've gone through the reports and haven't noticed any errors showup in our logs. Cheers!
