### ISSUE TITLE
Errors and Warnings on Postgres

### ISSUE THREAD

**Issue by cameorn1730** [intelliboard/intelliboard#21]
Hi, I'm Cameron from the MoodleCloud team. We're running the latest commit (e5de0ab69c4281d62b696fa58900ce65a5fffdc9) on our staging server. I've run through most of the reports and a few of them are still generating errors/warnings. Below is a summary of the files and the errors I saw:

https://au-app.intelliboard.net/reports/view/instructoractivityengagementdetail

Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n
Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 343 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 3197 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report81()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n

https://au-app.intelliboard.net/reports/view/InstructorDashboardUtilization

PHP Notice:  Undefined variable: sql_filter in /var/www/moodle361t/local/intelliboard/externallib.php on line 2094

https://au-app.intelliboard.net/reports/view/MoodleroomsNewOutcomes
https://au-app.intelliboard.net/reports/view/OutcomesAttemptReport
https://au-app.intelliboard.net/reports/view/certificatesgranted
https://au-app.intelliboard.net/reports/view/expiredcertificates
https://au-app.intelliboard.net/reports/view/ChecklistActivityReport?course=3
https://au-app.intelliboard.net/reports/view/ForumActivityDetails
https://au-app.intelliboard.net/reports/view/questionnairedata

Database transaction aborted automatically in /var/www/moodle361t/webservice/rest/server.php

https://au-app.intelliboard.net/reports/view/AttendanceOverview

PHP Notice:  Trying to get property 'debug' of non-object in /var/www/moodle361t/local/intelliboard/externallib.php on line 338

https://au-app.intelliboard.net/reports/view/LessonAnswers

Debugging: Did you remember to make the first column something unique in your call to get_records? Duplicate value '3' found in column 'id'. in \n* line 885 of /lib/dml/pgsql_native_moodle_database.php: call to debugging()\n* line 345 of /local/intelliboard/externallib.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 1482 of /local/intelliboard/externallib.php: call to local_intelliboard_external->get_report_data()\n* line 154 of /local/intelliboard/externallib.php: call to local_intelliboard_external->report18_graph()\n* line 1415 of /webservice/lib.php: call to local_intelliboard_external::database_query()\n* line 1261 of /webservice/lib.php: call to webservice_base_server->execute()\n* line 44 of /webservice/rest/server.php: call to webservice_base_server->run()\n

https://au-app.intelliboard.net/reports/view/poodll_plugin_instances
https://au-app.intelliboard.net/reports/view/poodll_recording_locations
https://au-app.intelliboard.net/reports/view/poodll_recordings

PHP Notice:  Trying to get property 'debug' of non-object in /var/www/moodle361t/local/intelliboard/externallib.php on line 338

**Comment by intelliboard** [comment]
Hi there is a new commit https://github.com/intelliboard/intelliboard/commit/deb553b6da5f1ba72327a7235e38659c4141329a
with bug fixes.

**Comment by cameorn1730** [comment]
After applying this commit, we don't see the warnings in our logs anymore, thanks! ☺️
