### ISSUE TITLE
Moodle 3.5/3.6 privacy compliance

### ISSUE THREAD

**Issue by dvdcastro** [intelliboard/intelliboard#23]
Hello,

There are new privacy APIs in latest versions of Moodle 3.5 and 3.6 that need to be implemented. It would be nice to have these features included.

### Taken from the [Privacy API page](https://docs.moodle.org/dev/Privacy_API#Standard_plugins_which_store_data)
In addition to existing requirements for GDPR compatible plugins, any plugin which implements the plugin provider interface must also implement the \core_privacy\local\request\core_userlist_provider interface. Two new methods need to be implemented:

* [get_users_in_context()](https://docs.moodle.org/dev/Privacy_API#Retrieving_the_users_in_a_context)
* [delete_data_for_users()](https://docs.moodle.org/dev/Privacy_API#Delete_personal_information_for_several_users_in_a_specific_context)

However, the two above methods are not required for plugins that implement the [null_provider](https://docs.moodle.org/dev/Privacy_API#Plugins_which_do_not_store_personal_data) only (i.e. which do not store personal data).

**Comment by intelliboard** [comment]
This is complete
