### ISSUE TITLE
JavaScript breaks when using IE11

### ISSUE THREAD

**Issue by haiksu** [intelliboard/intelliboard#33]
When using Moodle, that has local_intelliboard plugin installed, Moodle's javascript breaks and using Moodle becomes impossible.

Intelliboard plugin uses template literals -syntax (i.e. here https://github.com/intelliboard/intelliboard/blob/master/amd/src/setup_moodle_settings.js#L58), which isn't supported by Microsoft's Internet Explorer 11.

After removing local_intelliboard plugin from Moodle, Moodle works on IE11 normally.

**Comment by intelliboard** [comment]
Hello, please update the latest version, should be solved!

**Comment by haiksu** [comment]
Thank you for attending to this problem so quickly. One minor additional request - could you update the plugin on https://moodle.org/plugins too as our company uses that platform in automation?

https://moodle.org/plugins/pluginversions.php?plugin=local_intelliboard has still the non ie fix -version.
