### ISSUE TITLE
JavaScript breaks when using Moodle with IE11

### ISSUE THREAD

**Issue by haiksu** [intelliboard/intelliboard#34]
When using Moodle, that has local_intelliboard plugin installed, Moodle's javascript breaks and using Moodle becomes impossible.

Intelliboard plugin uses DOMTokenList.foreach() -function (i.e. here https://github.com/intelliboard/intelliboard/blob/master/amd/src/flatpickr.js#L2218), which isn't supported by Microsoft's Internet Explorer 11.

After removing local_intelliboard plugin from Moodle, Moodle works on IE11 normally.

**Comment by intelliboard** [comment]
Fixed in the current version.
