### ISSUE TITLE
Exception - Argument 1 passed to check_user_preferences_loaded() must be an instance of stdClass, null given, called in [dirroot]/lib/moodlelib.php on line 2158

### ISSUE THREAD

**Issue by ShiOis** [intelliboard/intelliboard#53]
I get this error when installing local_intelliboard7.0.0.0 on Moodle 4.0.5-4.1.0.
Details on the error are below.

> Exception - Argument 1 passed to check_user_preferences_loaded() must be an instance of stdClass, null given, called in 
> [dirroot]/lib/moodlelib.php on line 2158
> Debug info:
> Error code: generalexceptionmessage
> Stack trace:
> line 1897 of /lib/moodlelib.php: TypeError thrown
> line 2158 of /lib/moodlelib.php: call to check_user_preferences_loaded()
> line 307 of /local/intelliboard/lib.php: call to get_user_preferences()
> line 600 of /local/intelliboard/lib.php: call to local_intelliboard_insert_tracking()
> line 603 of /local/intelliboard/lib.php: call to local_intelliboard_init()
> line 866 of /lib/classes/component.php: call to include_once()
> line 7918 of /lib/moodlelib.php: call to core_component::get_plugin_list_with_file()
> line 831 of /lib/setup.php: call to get_plugins_with_function()
> line 912 of /config.php: call to require_once()
> line 94 of /admin/index.php: call to require()

**Comment by guillogo** [comment]
Hi, we're getting the same error in multiple Moodle versions, I've created this Merge Request to fix it -> https://github.com/intelliboard/intelliboard/pull/54
